### ISSUE TITLE
Eliminate punctuation and case sensitivity in tweet preprocessing

### ISSUE THREAD

**Issue by magsol** [quinngroup/download_twitter_disease_data#2]
There should be a simple `str_replace` method for which you can provide punctuation, and the "replace" character is just a 0-length string, i.e. `''`.

Also, make sure all the text is `lower()` or `upper()` before using it.

**Comment by patrickbreen** [comment]
I just committed an update where I use `string.punctuation` to strip out punctuation, and I have `lower()`
